[build]
  command = "NODE_ENV=production NEXT_TELEMETRY_DISABLED=1 mkdir -p .next/sqlite && chmod -R 777 .next/sqlite && touch .next/sqlite/prisma.db && chmod 666 .next/sqlite/prisma.db && npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20.10.0"
  NPM_FLAGS = "--no-audit --no-fund --legacy-peer-deps"
  NEXT_TELEMETRY_DISABLED = "1"
  DATABASE_URL = "file:./.next/sqlite/prisma.db"
  NEXTAUTH_URL = "https://museterasistema.netlify.app"
  NEXTAUTH_SECRET = "musicoterapia_secret_key_2024"
  NEXT_PUBLIC_SITE_URL = "https://museterasistema.netlify.app"
  NODE_ENV = "production"
  CI = "true"
  NEXT_IGNORE_TYPE_ERROR = "1"
  NEXT_IGNORE_ESLINT_ERROR = "1"
  NEXT_SHARP_PATH = "/tmp/node_modules/sharp"

[build.processing]
  skip_processing = true

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    skipBuildCache = true
    skipImageOptimization = true
    skipTypeCheck = true

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = [".next/sqlite/**"]

[[redirects]]
  from = "/*"
  to = "/_next/static/:splat"
  status = 200
  force = false
  conditions = {Path = "/_next/static/**"}

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
