[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20.10.0"
  NPM_FLAGS = "--no-audit --no-fund --legacy-peer-deps"
  NEXT_TELEMETRY_DISABLED = "1"
  DATABASE_URL = "file:./.next/sqlite/prisma.db"
  NEXTAUTH_URL = "https://museterasistema.netlify.app"
  NEXTAUTH_SECRET = "musicoterapia_secret_key_2024"
  NEXT_PUBLIC_SITE_URL = "https://museterasistema.netlify.app"
  NODE_ENV = "production"
  CI = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = [".next/sqlite/**"]

[[redirects]]
  from = "/*"
  to = "/_next/static/:splat"
  status = 200
  force = false
  conditions = {Path = "/_next/static/**"}

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
